language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_script:
  - npm install -g coveralls
script:
   - npm run ci
branches:
  only:
    - master
after_success:
  - cat ./coverage/lcov.info | coveralls
